### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by redtachyons** [abhijithdj007/Scrapper#1]
Hi Abhijith,
I have couple of doubts regarding the project

1. It seems that you are using tab for indentation and it is broken in many places, any specific reason for not using preferred 2 space indentation

2. I can not see any test files in this repo

3. Any specific reason to store rank in `user_domain_scraps` join table? rank will be same for same website for all users, right ?

4. Any specific reason for using ```all.each``` instead of ```find_each``` which is better for large set of data

5. Is return needed here https://github.com/abhijithdj007/Scrapper/blob/master/app/models/user_domain_scrap.rb#L12

6. https://github.com/abhijithdj007/Scrapper/blob/master/app/models/domain.rb#L13 this method is supposed to be private, right?

7. Can I edit website details from active admin console, it seems like you added users list only

8. Can you use some constants like ```role == ADMIN``` instead of matching with numbers like 0

Regards
Aboobacker

**Comment by abhijithdj007** [comment]
Hi Aboobacker,

Thanks for the review of code.

1. It seems that you are using tab for indentation and it is broken in many places, any specific reason for not using preferred 2 space indentation
 -> Since m using sublime 3 editor. it is taking care of indentation by default as tab. 

2. I can not see any test files in this repo
 -> Since i had a busy schedule i was not able to write any test cases. I can write and push test case this week end if necessary.

3. Any specific reason to store rank in user_domain_scraps join table? rank will be same for same website for all users, right ?
-> Yes. Keeping a large scale application in mind, i have designed this structure.
 1. If i make structure with only user and scrapped_information table, then i wont have any history of rank changes. So while doing graph i will only have previous and present rank.
 2. Making separte table with domain, user and scapped information will also help in getting to know user and domain rank history. Also lessen repetition of domain ranking.
 3. And if any changes comes tomorrow, it will be much easier to do.Any kind of changes in this structure. 

4. Any specific reason for using all.each instead of find_each which is better for large set of data
 -> find_each is much better. Since small amount of data is avaliable i have used all.each

5. Is return needed here https://github.com/abhijithdj007/Scrapper/blob/master/app/models/user_domain_scrap.rb#L12
 -> Yes return is needed here. because it contains more than 1 variable. else will give error. 

6. https://github.com/abhijithdj007/Scrapper/blob/master/app/models/domain.rb#L13 this method is supposed to be private, right?
 -> Yes.

7. Can I edit website details from active admin console, it seems like you added users list only
    -> Yes. we can edit. since i thought only user manage is required i have not create other model show and form in active admin folders.
     If we want to do any CRUD opertion, then we need to create file in app/admin. After creating we need to specfic which are the fields you want to display. And if edit form if required then add them also.

8. Can you use some constants like role == ADMIN instead of matching with numbers like 0 
-> Yes. we can.
In user model we should create "enum roles: [:admin, :user]"
then we can write current_user.roles == 'admin'
or 
we can create a method which will check current_user is admin or not in user model

Regards,
Abhijith

**Comment by redtachyons** [comment]
>  Since m using sublime 3 editor. it is taking care of indentation by default as tab.

You can configure two space indentation in sublime :-)

> Since i had a busy schedule i was not able to write any test cases. I can write and push test case this week end if necessary.

That will be great

> Any specific reason to store rank in user_domain_scraps join table? rank will be same for same website for all users, right ?
> -> Yes. Keeping a large scale application in mind, i have designed this structure.

But it actually causes duplicate data, right? because a domain has many ```	has_many :user_domain_scraps ``` and all of those will have same rank for a particular day

> Is return needed here https://github.com/abhijithdj007/Scrapper/blob/master/app/models/user_domain_scrap.rb#L12
> -> Yes return is needed here. because it contains more than 1 variable. else will give error.

You can just write [var1, var2]

**Comment by redtachyons** [comment]
> Yes. Keeping a large scale application in mind, i have designed this structure.

Conflicting with

> find_each is much better. Since small amount of data is avaliable i have used all.each

:-)

**Comment by abhijithdj007** [comment]
thanks for the review comment @Aboobacker.

Will write test cases and update you this weekend.

Would like to say something regarding this :)
Any specific reason to store rank in user_domain_scraps join table? rank will be same for same website for all users, right ?
    -> Yes. Keeping a large scale application in mind, i have designed this structure.

But it actually causes duplicate data, right? because a domain has many has_many :user_domain_scraps and all of those will have same rank for a particular day
-> In a particular day there might be rank changes more than once. If there is no such case. then i can find whether that domain is scrapped for that particular day and will take necessary data from database

**Comment by nithinbekal** [comment]
Thanks for clearing that, @abhijithdj007.

I think what @redtachyons was referring to is that you needn't associate scraping history with user. You're right that it's better to keep the history in a separate table, but even if you wan't to store ranks at different points in time, it will still be unique for all users.

Just a side note re: indentation: I recommend using [Rubocop](https://github.com/bbatsov/rubocop) for checking such issues before committing code.

**Comment by redtachyons** [comment]
Yes, I was referring to the same issue, 

BTW you mistakenly tagged another user and he will get notification email for mentioning here :-)

**Comment by aboobacker** [comment]
Sorry guys, but I was not involved in this discussion. Please un-tag me.


Kind Regards,

*Aboobacker P Ummer*
Website developer/SEO specialist
+971 52 898 2133 (*UAE*)
+91 964 575 6431 (*INDIA*)
http://aboobacker.com
